# .github/workflows/build-and-push.yml
name: Build and push

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build-and-push-images:
    strategy:
      matrix:
        service: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
      - name: Check inputs
        if: ${{ inputs.environment != 'dev' && inputs.environment != 'prod' }}
        run: echo "Wrong environment. Expected 'dev' or 'prod', got '${{ inputs.environment }}'" && exit 1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t healthcheck-${{ matrix.service }}:${{ inputs.environment }} ${{ matrix.service }}
          docker push healthcheck-${{ matrix.service }}:${{ inputs.environment }}
