name: Compile and push dev images

on:
  push:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push dev images
        uses: .github/workflows/build-and-push.yml
        with:
          environment: "dev"
