name: Compile and push prod images

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push prod images
        uses: ./.github/actions/build-and-push
        with:
          environment: "prod"
          service: ${{ matrix.service }}

