name: Tests

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - reopened

jobs:
  backend_integration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/tests/integration
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run backend, APIgateway and database services in a dedicated container
        run: docker compose -f docker-compose.yml up -d
      - name: Install dependencies
        run: npm i
      - name: Run backend tests
        run: npm run test

